// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4yMbEMJy_Vf5mHBnXrVVYXUohUZfSzVg',
    appId: '1:126648573361:web:f90e74a3aa917d4f223190',
    messagingSenderId: '126648573361',
    projectId: 'auth-news-43598',
    authDomain: 'auth-news-43598.firebaseapp.com',
    storageBucket: 'auth-news-43598.appspot.com',
    measurementId: 'G-6XGWQSNHQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq6eJ4l9M1aZBuWX-gEOduQXOukQ60YpM',
    appId: '1:126648573361:android:9863c43d99310162223190',
    messagingSenderId: '126648573361',
    projectId: 'auth-news-43598',
    storageBucket: 'auth-news-43598.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjcaUGlUKd00YJxUXbYwS_3PTzvLHsGoA',
    appId: '1:126648573361:ios:14aa2da0d3a91dde223190',
    messagingSenderId: '126648573361',
    projectId: 'auth-news-43598',
    storageBucket: 'auth-news-43598.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjcaUGlUKd00YJxUXbYwS_3PTzvLHsGoA',
    appId: '1:126648573361:ios:5ae05e447bb17b76223190',
    messagingSenderId: '126648573361',
    projectId: 'auth-news-43598',
    storageBucket: 'auth-news-43598.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
